#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 0dd483d8-7ebf-4a67-aa34-a5cd9e00fec9
# Source File: leGUI.psf
#------------------------------------------------------------------------
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
QgkAAB+LCAAAAAAABABllsfK68gWhecGv8Ohp4JWsJXg7wPKWbZymCkHK2fp6dv33MmFW6OiioJV
7L2+vX7MLOm3bDrZaIl+fTdz1Xf//PX4G/7r9/3269fPa6qKqosavmoyPWqz300mONLfw5z/gP93
9+cF30/t7/wRcfCBfhy+pyjmxTLUfxdNsUsnwBtWB85Bkm+ky6RMgnopsMTRccc1zuNFDPw6QnHP
buUYAT2OeYuIx+T3W95jdjPZQd3qjNBitdu4Q+xfMwG8EgIinp1IHmAfrJUXgGBLBSjwYQvk8glF
uR5cwE3dAAKRIII9jN1v8F5t0ECmBZhtU8e9k8yqCUENsDPNfU/L6NMWCEbhtIQrMHpUEaohyCt7
bo7+1tRjP1q9WMFY6viBvd8QmdReUCC53VciaKOXhJf5prEsqR+d/VEYJ6RhgW+dj+YLClTKyzLv
ratBusRT+fWZECYQOEG0p1G43172E8wONNLfjpfF1LViwcQnWEhfT+1MVbCGnoGdIWsQgMv+aUEI
BVIhXaJnWuArI8iqX8Fv0L7eD3u532J916kGRzoKlHEg7XAVfBvPLc1Mxy5mpX6RZnlCZbp2hKQT
BV8yeN4asNgTlg8vaIlzAEbntWljIXS/1dkRB646tvMhlbkwoAQEvE1hmi4WYOsKLEs8cfjBMet3
N8LbFe52F6leGwIOp8kdQWOWGtgkgWvXer8l1OV2q5rViGSo2gcp+JzKw7GmBPEA2ZMjdb94T1AA
alS2FeKhMq7ZJSuPn1HhR6IOpU0yQDMa8S/rfrserdYDlpYXQjk8WOGF7ktG9jC9hsCpFA5KnkAj
C4hNT5rK+Gr62ae6eVqLEhysYZlKI6Cia7JwQgT325HNWKtOj816GLUfeXEq9ylgFsd5OIIKUd2c
VFb0gbVhnEPmjfS0qSsfMrdp7TEo0+pZWaFXufvZ2K+21OMozaKNeqQ0o+mJ2sqS2hsYRTvRzFtd
dHUY2KvAdXhdYS5VfVB5ny4cDF6nxe6ZUuUmPM2LlyJu+3ZIX0Mvc9dUeTQzRvhkpfwgh6Bw3J23
Po3TabQUigHMQzL9CgvQhnEMHvUH5UiBqBKtzQehaBokjUz7/SYm5hy1gexROam5MB0nwcv9cJki
xh7r02PCxwXNDbQ5siSScBIUhigSHsYIwUAsy9g6E8RlELTUEOD9hsPy4ZRRcvSd4cjnmVwFOD0n
xsFA3znOjUfxzOw/bR9m874cJ24kO1AYsm4smB4Kga9s46Vic+AV8/1mOPVDdxF7KrnGybeKKRzC
sXoxa6T62k5bgf5DG/ZLm+yay7Q8xOKSnshWhZ7QoB0KXQL9tYedtszj22+ZhU87pnVwg665p3st
tmYizkVIzqbjOPXcYwIoGQsRJ1WWqfW11pMi7MwcyL3ycH5xgtZlpRTU4/t+A4HMMOQdxIscaXA4
mhuh6XeFNDM5ti0q8WtM4eRgxDEOnpx617VhCSeSQBcUjcNdcn1smV7Qc8xm7n4LzwnyZWI1AHdM
M7cAOw+jRNSqI0t4x7QIwI18Zrz8UYr6Qil9zXWZknLeHjIst0zkUfAACp0NABpfIr1Rw68sufK7
aHozgF1T+jgwCGP2kT7LaqICVXzMTiN3KKcUdC2zIxcOgom7icgmQqNen2h7S58WfX1/qgSdiJIk
BXBFAyeoRpziI0UwDTKs2ZzhHsOYRqal6fPsLAFUnFgWlNeHGq3ZqfArqmsNL11GeqWZVd5vBBfQ
PSyjn/HZxizulGaqCTsAK9aU14UHv9o5hEVYH3U3f1udM/Hhk8ZieNpid6SFtoQqDlVxylAd6n6b
IKkiBDcaD1ZRDHsyzg9n+aKn9LbPjByjcagieVUJWT3XebLCYF8Suy9YeVpfmAZK72H9EmG9Tk3j
l+RfnUgwn5MjP+Ons79yqi3G5mJhNJaiOpuFwi0+e8mymGM01ObZAGGMBVXLusXwQ79QAz2gxRjx
eXW/dTBQV2MX8YHaTyGzGG2hwPx0zA1vwNjTOPs4cSuBWCDZqPTDKiM6Qpv8lEfdE2GrYHHzJJNu
LHB5uN/ILwuLfaJeTEP2kiuMOwlZYwPJ35llk87KfSbvOcJWRgOEFwVoFg+Tu29NtSnvsSxfvSoC
O43ZSLlN99t5RRHG+p4CRs23unme9moaDCQZ+FseRmCOYevWDQBOy86YkoOPw1ati9osSBtMwr76
RLV9qSExt91vTYm3Sjy4njycB+OWQPWw49oFCWllcl/t/EMoA+NKAaR7JOmq29ZBHLUiTYUE5Ev8
gkWJgd+EdEVJ+/Wp6uICRExJMZ2pBpulM4/LZaN80SSPauiaXJKnyAA9xUy9CCcl5ciE+cFvTlkb
xxt7yA+HmvV1nrcF/nphdt3IN1rNtZYoGb8DB/sSjhfjNcjebyK68qcofgpvhOnoG1P++QH/xJg/
gYaa56yNmyqbf4Hfkx/wfzPT738Bpx0je0IJAAA=#>
#endregion

<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       15/03/2022 09:52
     Generated by:       Nathan
    --------------------------------------------------------------------------------
    .DESCRIPTION
        GUI script generated by PowerShell Studio 2020
#>


#----------------------------------------------
#region Application Functions
#----------------------------------------------

#endregion Application Functions

#----------------------------------------------
# Generated Form Function
#----------------------------------------------
function Show-leGUI_psf {

	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$form1 = New-Object 'System.Windows.Forms.Form'
	$button1 = New-Object 'System.Windows.Forms.Button'
	$picturebox1 = New-Object 'System.Windows.Forms.PictureBox'
	$Vidya = New-Object 'System.Windows.Forms.GroupBox'
	$btnAccelerate = New-Object 'System.Windows.Forms.Button'
	$btnCountVideo = New-Object 'System.Windows.Forms.Button'
	$panel6 = New-Object 'System.Windows.Forms.Panel'
	$lblVideo = New-Object 'System.Windows.Forms.Label'
	$labelVideoFilesDetected = New-Object 'System.Windows.Forms.Label'
	$grpbxMusic = New-Object 'System.Windows.Forms.GroupBox'
	$panelMusic = New-Object 'System.Windows.Forms.Panel'
	$panel10 = New-Object 'System.Windows.Forms.Panel'
	$txtTitle4 = New-Object 'System.Windows.Forms.TextBox'
	$txtArtist4 = New-Object 'System.Windows.Forms.TextBox'
	$label5 = New-Object 'System.Windows.Forms.Label'
	$label6 = New-Object 'System.Windows.Forms.Label'
	$panel9 = New-Object 'System.Windows.Forms.Panel'
	$txtTitle3 = New-Object 'System.Windows.Forms.TextBox'
	$txtArtist3 = New-Object 'System.Windows.Forms.TextBox'
	$label3 = New-Object 'System.Windows.Forms.Label'
	$label4 = New-Object 'System.Windows.Forms.Label'
	$panel8 = New-Object 'System.Windows.Forms.Panel'
	$txtTitle2 = New-Object 'System.Windows.Forms.TextBox'
	$txtArtist2 = New-Object 'System.Windows.Forms.TextBox'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$label2 = New-Object 'System.Windows.Forms.Label'
	$panel1 = New-Object 'System.Windows.Forms.Panel'
	$txtTitle1 = New-Object 'System.Windows.Forms.TextBox'
	$txtArtist1 = New-Object 'System.Windows.Forms.TextBox'
	$labelArtist = New-Object 'System.Windows.Forms.Label'
	$labelTitle = New-Object 'System.Windows.Forms.Label'
	$btnCountMusic = New-Object 'System.Windows.Forms.Button'
	$panel5 = New-Object 'System.Windows.Forms.Panel'
	$lblMusic = New-Object 'System.Windows.Forms.Label'
	$labelMusicFilesDetected = New-Object 'System.Windows.Forms.Label'
	$progressbar1 = New-Object 'System.Windows.Forms.ProgressBar'
	$btnCompile = New-Object 'System.Windows.Forms.Button'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	Add-Type -AssemblyName System.Windows.Forms
	
	$form1_Load = {
		#TODO: Place custom script here
		
		$jsonObject = Get-Content -Path .\soustitres.json | ConvertFrom-Json
		$titles = $jsonObject.Titles
		$artists = $jsonObject.Artists
		
		$txtTitle1.Text = $titles.1
		$txtTitle2.Text = $titles.2
		$txtTitle3.Text = $titles.3
		$txtTitle4.Text = $titles.4
		
		$txtArtist1.Text = $artists.1
		$txtArtist2.Text = $artists.2
		$txtArtist3.Text = $artists.3
		$txtArtist4.Text = $artists.4
		
		$lblVideo.Text = (Get-ChildItem -Path .\videos | Measure-Object).Count
		$lblMusic.Text = (Get-ChildItem -Path .\musiques | Measure-Object).Count
	}
	
	$labelArtist_Click={
		#TODO: Place custom script here
		
	}
	
	$grpbxMusic_Enter={
		#TODO: Place custom script here
		
	}
	
	$panel1_Paint=[System.Windows.Forms.PaintEventHandler]{
	#Event Argument: $_ = [System.Windows.Forms.PaintEventArgs]
		#TODO: Place custom script here
		
	}
	
	$labelMusicFilesDetected_Click={
		#TODO: Place custom script here
		
	}
	
	$txtArtist1_TextChanged={
		#TODO: Place custom script here
		
	}
	
	$btnCountMusic_Click={
		#TODO: Place custom script here
		$lblMusic.Text = (Get-ChildItem -Path .\musiques | Measure-Object).Count
	}
	
	$btnCompile_Click={
		#TODO: Get text in panels and add to music files
		
		$myObject = [PSCustomObject]@{
			Titles = [PSCustomObject]@{
				1 = $txtTitle1.Text
				2 = $txtTitle2.Text
				3 = $txtTitle3.Text
				4 = $txtTitle4.Text
			}
			Artists = [PSCustomObject]@{
				1 = $txtArtist1.Text
				2 = $txtArtist2.Text
				3 = $txtArtist3.Text
				4 = $txtArtist4.Text
			}
		}
		
		$myObject = ConvertTo-Json $myObject
		$myObject | Out-File .\soustitres.json
		
		Invoke-Expression -Command .\editing.ps1
	}
	
	$picturebox1_Click={
		#TODO: Place custom script here
		
		$FileBrowser = New-Object System.Windows.Forms.OpenFileDialog -Property @{
			InitialDirectory = [Environment]::GetFolderPath('Desktop')
			Filter		     = 'PNG Image (*.png)|*.png|JPEG Image (*.jpg)|*.jpg,*.jpeg'
		}
		$null = $FileBrowser.ShowDialog()
		$picturebox1.Image = [System.Drawing.Bitmap]::FromFile($FileBrowser.FileName)
	}
	
	#region Control Helper Functions
	function Show-NotifyIcon
	{
	<#
		.SYNOPSIS
			Displays a NotifyIcon's balloon tip message in the taskbar's notification area.
		
		.DESCRIPTION
			Displays a NotifyIcon's a balloon tip message in the taskbar's notification area.
			
		.PARAMETER NotifyIcon
	     	The NotifyIcon control that will be displayed.
		
		.PARAMETER BalloonTipText
	     	Sets the text to display in the balloon tip.
		
		.PARAMETER BalloonTipTitle
			Sets the Title to display in the balloon tip.
		
		.PARAMETER BalloonTipIcon	
			The icon to display in the ballon tip.
		
		.PARAMETER Timeout	
			The time the ToolTip Balloon will remain visible in milliseconds. 
			Default: 0 - Uses windows default.
	#>
		 param(
		  [Parameter(Mandatory = $true, Position = 0)]
		  [ValidateNotNull()]
		  [System.Windows.Forms.NotifyIcon]$NotifyIcon,
		  [Parameter(Mandatory = $true, Position = 1)]
		  [ValidateNotNullOrEmpty()]
		  [String]$BalloonTipText,
		  [Parameter(Position = 2)]
		  [String]$BalloonTipTitle = '',
		  [Parameter(Position = 3)]
		  [System.Windows.Forms.ToolTipIcon]$BalloonTipIcon = 'None',
		  [Parameter(Position = 4)]
		  [int]$Timeout = 0
	 	)
		
		if($null -eq $NotifyIcon.Icon)
		{
			#Set a Default Icon otherwise the balloon will not show
			$NotifyIcon.Icon = [System.Drawing.Icon]::ExtractAssociatedIcon([System.Windows.Forms.Application]::ExecutablePath)
		}
		
		$NotifyIcon.ShowBalloonTip($Timeout, $BalloonTipTitle, $BalloonTipText, $BalloonTipIcon)
	}
	
	
	#endregion
	
	$label1_Click={
		#TODO: Place custom script here
		
	}
	
	$btnCountVideo_Click={
		#TODO: Place custom script here
		$lblVideo.Text = (Get-ChildItem -Path .\videos | Measure-Object).Count
	}
	
	$lblMusic_Click={
		#TODO: Place custom script here
	}
	
	$button1_Click={
		#TODO: Place custom script here
		
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$form1.WindowState = $InitialFormWindowState
	}
	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$button1.remove_Click($button1_Click)
			$picturebox1.remove_Click($picturebox1_Click)
			$btnCountVideo.remove_Click($btnCountVideo_Click)
			$labelVideoFilesDetected.remove_Click($labelMusicFilesDetected_Click)
			$txtArtist4.remove_TextChanged($txtArtist1_TextChanged)
			$panel10.remove_Paint($panel1_Paint)
			$txtArtist3.remove_TextChanged($txtArtist1_TextChanged)
			$panel9.remove_Paint($panel1_Paint)
			$txtArtist2.remove_TextChanged($txtArtist1_TextChanged)
			$panel8.remove_Paint($panel1_Paint)
			$txtArtist1.remove_TextChanged($txtArtist1_TextChanged)
			$panel1.remove_Paint($panel1_Paint)
			$btnCountMusic.remove_Click($btnCountMusic_Click)
			$lblMusic.remove_Click($lblMusic_Click)
			$labelMusicFilesDetected.remove_Click($labelMusicFilesDetected_Click)
			$grpbxMusic.remove_Enter($grpbxMusic_Enter)
			$btnCompile.remove_Click($btnCompile_Click)
			$form1.remove_Load($form1_Load)
			$form1.remove_Load($Form_StateCorrection_Load)
			$form1.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$form1.SuspendLayout()
	$Vidya.SuspendLayout()
	$panel6.SuspendLayout()
	$grpbxMusic.SuspendLayout()
	$panelMusic.SuspendLayout()
	$panel10.SuspendLayout()
	$panel9.SuspendLayout()
	$panel8.SuspendLayout()
	$panel1.SuspendLayout()
	$panel5.SuspendLayout()
	#
	# form1
	#
	$form1.Controls.Add($button1)
	$form1.Controls.Add($picturebox1)
	$form1.Controls.Add($Vidya)
	$form1.Controls.Add($grpbxMusic)
	$form1.Controls.Add($progressbar1)
	$form1.Controls.Add($btnCompile)
	$form1.AutoScaleDimensions = '8, 17'
	$form1.AutoScaleMode = 'Font'
	$form1.ClientSize = '695, 575'
	$form1.Name = 'form1'
	$form1.Text = 'Form'
	$form1.add_Load($form1_Load)
	#
	# button1
	#
	$button1.Location = '466, 173'
	$button1.Margin = '4, 4, 4, 4'
	$button1.Name = 'button1'
	$button1.Size = '100, 30'
	$button1.TabIndex = 6
	$button1.Text = 'button1'
	$button1.UseCompatibleTextRendering = $True
	$button1.UseVisualStyleBackColor = $True
	$button1.add_Click($button1_Click)
	#
	# picturebox1
	#
	$picturebox1.Cursor = 'Hand'
	$picturebox1.Location = '359, 215'
	$picturebox1.Margin = '4, 4, 4, 4'
	$picturebox1.Name = 'picturebox1'
	$picturebox1.Size = '315, 315'
	$picturebox1.TabIndex = 5
	$picturebox1.TabStop = $False
	$picturebox1.add_Click($picturebox1_Click)
	#
	# Vidya
	#
	$Vidya.Controls.Add($btnAccelerate)
	$Vidya.Controls.Add($btnCountVideo)
	$Vidya.Controls.Add($panel6)
	$Vidya.Location = '351, 13'
	$Vidya.Margin = '4, 4, 4, 4'
	$Vidya.Name = 'Vidya'
	$Vidya.Padding = '4, 4, 4, 4'
	$Vidya.Size = '331, 152'
	$Vidya.TabIndex = 4
	$Vidya.TabStop = $False
	$Vidya.Text = 'Vidya'
	$Vidya.UseCompatibleTextRendering = $True
	#
	# btnAccelerate
	#
	$btnAccelerate.Location = '8, 78'
	$btnAccelerate.Margin = '4, 4, 4, 4'
	$btnAccelerate.Name = 'btnAccelerate'
	$btnAccelerate.Size = '315, 67'
	$btnAccelerate.TabIndex = 11
	$btnAccelerate.Text = 'Accelerate'
	$btnAccelerate.UseCompatibleTextRendering = $True
	$btnAccelerate.UseVisualStyleBackColor = $True
	#
	# btnCountVideo
	#
	$btnCountVideo.Location = '223, 32'
	$btnCountVideo.Margin = '4, 4, 4, 4'
	$btnCountVideo.Name = 'btnCountVideo'
	$btnCountVideo.Size = '100, 30'
	$btnCountVideo.TabIndex = 10
	$btnCountVideo.Text = 'Count'
	$btnCountVideo.UseCompatibleTextRendering = $True
	$btnCountVideo.UseVisualStyleBackColor = $True
	$btnCountVideo.add_Click($btnCountVideo_Click)
	#
	# panel6
	#
	$panel6.Controls.Add($lblVideo)
	$panel6.Controls.Add($labelVideoFilesDetected)
	$panel6.Location = '8, 24'
	$panel6.Margin = '4, 4, 4, 4'
	$panel6.Name = 'panel6'
	$panel6.Size = '207, 46'
	$panel6.TabIndex = 8
	#
	# lblVideo
	#
	$lblVideo.AutoSize = $True
	$lblVideo.Location = '180, 12'
	$lblVideo.Margin = '4, 0, 4, 0'
	$lblVideo.Name = 'lblVideo'
	$lblVideo.Size = '17, 21'
	$lblVideo.TabIndex = 7
	$lblVideo.Text = '...'
	$lblVideo.UseCompatibleTextRendering = $True
	#
	# labelVideoFilesDetected
	#
	$labelVideoFilesDetected.AutoSize = $True
	$labelVideoFilesDetected.Font = 'Open Sans, 9pt, style=Bold'
	$labelVideoFilesDetected.Location = '8, 12'
	$labelVideoFilesDetected.Margin = '4, 0, 4, 0'
	$labelVideoFilesDetected.Name = 'labelVideoFilesDetected'
	$labelVideoFilesDetected.Size = '162, 26'
	$labelVideoFilesDetected.TabIndex = 6
	$labelVideoFilesDetected.Text = 'Video files detected:'
	$labelVideoFilesDetected.UseCompatibleTextRendering = $True
	$labelVideoFilesDetected.add_Click($labelMusicFilesDetected_Click)
	#
	# grpbxMusic
	#
	$grpbxMusic.Controls.Add($panelMusic)
	$grpbxMusic.Controls.Add($btnCountMusic)
	$grpbxMusic.Controls.Add($panel5)
	$grpbxMusic.Location = '13, 13'
	$grpbxMusic.Margin = '4, 4, 4, 4'
	$grpbxMusic.Name = 'grpbxMusic'
	$grpbxMusic.Padding = '4, 4, 4, 4'
	$grpbxMusic.Size = '331, 517'
	$grpbxMusic.TabIndex = 3
	$grpbxMusic.TabStop = $False
	$grpbxMusic.Text = 'Music blurbs'
	$grpbxMusic.UseCompatibleTextRendering = $True
	$grpbxMusic.add_Enter($grpbxMusic_Enter)
	#
	# panelMusic
	#
	$panelMusic.Controls.Add($panel10)
	$panelMusic.Controls.Add($panel9)
	$panelMusic.Controls.Add($panel8)
	$panelMusic.Controls.Add($panel1)
	$panelMusic.Location = '8, 70'
	$panelMusic.Margin = '4, 4, 4, 4'
	$panelMusic.Name = 'panelMusic'
	$panelMusic.Size = '315, 439'
	$panelMusic.TabIndex = 10
	#
	# panel10
	#
	$panel10.Controls.Add($txtTitle4)
	$panel10.Controls.Add($txtArtist4)
	$panel10.Controls.Add($label5)
	$panel10.Controls.Add($label6)
	$panel10.Location = '7, 328'
	$panel10.Margin = '4, 4, 4, 4'
	$panel10.Name = 'panel10'
	$panel10.Size = '304, 100'
	$panel10.TabIndex = 7
	$panel10.add_Paint($panel1_Paint)
	#
	# txtTitle4
	#
	$txtTitle4.Location = '76, 4'
	$txtTitle4.Margin = '4, 4, 4, 4'
	$txtTitle4.Multiline = $True
	$txtTitle4.Name = 'txtTitle4'
	$txtTitle4.Size = '224, 50'
	$txtTitle4.TabIndex = 2
	#
	# txtArtist4
	#
	$txtArtist4.Location = '76, 62'
	$txtArtist4.Margin = '4, 4, 4, 4'
	$txtArtist4.Multiline = $True
	$txtArtist4.Name = 'txtArtist4'
	$txtArtist4.Size = '224, 30'
	$txtArtist4.TabIndex = 3
	$txtArtist4.add_TextChanged($txtArtist1_TextChanged)
	#
	# label5
	#
	$label5.AutoSize = $True
	$label5.Font = 'Open Sans, 9pt, style=Bold'
	$label5.Location = '4, 66'
	$label5.Margin = '4, 0, 4, 0'
	$label5.Name = 'label5'
	$label5.Size = '49, 26'
	$label5.TabIndex = 6
	$label5.Text = 'Artist'
	$label5.UseCompatibleTextRendering = $True
	#
	# label6
	#
	$label6.AutoSize = $True
	$label6.Font = 'Open Sans, 9pt, style=Bold'
	$label6.Location = '4, 18'
	$label6.Margin = '4, 0, 4, 0'
	$label6.Name = 'label6'
	$label6.Size = '40, 26'
	$label6.TabIndex = 5
	$label6.Text = 'Title'
	$label6.UseCompatibleTextRendering = $True
	#
	# panel9
	#
	$panel9.Controls.Add($txtTitle3)
	$panel9.Controls.Add($txtArtist3)
	$panel9.Controls.Add($label3)
	$panel9.Controls.Add($label4)
	$panel9.Location = '8, 220'
	$panel9.Margin = '4, 4, 4, 4'
	$panel9.Name = 'panel9'
	$panel9.Size = '304, 100'
	$panel9.TabIndex = 7
	$panel9.add_Paint($panel1_Paint)
	#
	# txtTitle3
	#
	$txtTitle3.Location = '76, 4'
	$txtTitle3.Margin = '4, 4, 4, 4'
	$txtTitle3.Multiline = $True
	$txtTitle3.Name = 'txtTitle3'
	$txtTitle3.Size = '224, 50'
	$txtTitle3.TabIndex = 2
	#
	# txtArtist3
	#
	$txtArtist3.Location = '76, 62'
	$txtArtist3.Margin = '4, 4, 4, 4'
	$txtArtist3.Multiline = $True
	$txtArtist3.Name = 'txtArtist3'
	$txtArtist3.Size = '224, 30'
	$txtArtist3.TabIndex = 3
	$txtArtist3.add_TextChanged($txtArtist1_TextChanged)
	#
	# label3
	#
	$label3.AutoSize = $True
	$label3.Font = 'Open Sans, 9pt, style=Bold'
	$label3.Location = '4, 66'
	$label3.Margin = '4, 0, 4, 0'
	$label3.Name = 'label3'
	$label3.Size = '49, 26'
	$label3.TabIndex = 6
	$label3.Text = 'Artist'
	$label3.UseCompatibleTextRendering = $True
	#
	# label4
	#
	$label4.AutoSize = $True
	$label4.Font = 'Open Sans, 9pt, style=Bold'
	$label4.Location = '4, 18'
	$label4.Margin = '4, 0, 4, 0'
	$label4.Name = 'label4'
	$label4.Size = '40, 26'
	$label4.TabIndex = 5
	$label4.Text = 'Title'
	$label4.UseCompatibleTextRendering = $True
	#
	# panel8
	#
	$panel8.Controls.Add($txtTitle2)
	$panel8.Controls.Add($txtArtist2)
	$panel8.Controls.Add($label1)
	$panel8.Controls.Add($label2)
	$panel8.Location = '7, 112'
	$panel8.Margin = '4, 4, 4, 4'
	$panel8.Name = 'panel8'
	$panel8.Size = '304, 100'
	$panel8.TabIndex = 7
	$panel8.add_Paint($panel1_Paint)
	#
	# txtTitle2
	#
	$txtTitle2.Location = '76, 4'
	$txtTitle2.Margin = '4, 4, 4, 4'
	$txtTitle2.Multiline = $True
	$txtTitle2.Name = 'txtTitle2'
	$txtTitle2.Size = '224, 50'
	$txtTitle2.TabIndex = 2
	#
	# txtArtist2
	#
	$txtArtist2.Location = '76, 62'
	$txtArtist2.Margin = '4, 4, 4, 4'
	$txtArtist2.Multiline = $True
	$txtArtist2.Name = 'txtArtist2'
	$txtArtist2.Size = '224, 30'
	$txtArtist2.TabIndex = 3
	$txtArtist2.add_TextChanged($txtArtist1_TextChanged)
	#
	# label1
	#
	$label1.AutoSize = $True
	$label1.Font = 'Open Sans, 9pt, style=Bold'
	$label1.Location = '4, 66'
	$label1.Margin = '4, 0, 4, 0'
	$label1.Name = 'label1'
	$label1.Size = '49, 26'
	$label1.TabIndex = 6
	$label1.Text = 'Artist'
	$label1.UseCompatibleTextRendering = $True
	#
	# label2
	#
	$label2.AutoSize = $True
	$label2.Font = 'Open Sans, 9pt, style=Bold'
	$label2.Location = '4, 18'
	$label2.Margin = '4, 0, 4, 0'
	$label2.Name = 'label2'
	$label2.Size = '40, 26'
	$label2.TabIndex = 5
	$label2.Text = 'Title'
	$label2.UseCompatibleTextRendering = $True
	#
	# panel1
	#
	$panel1.Controls.Add($txtTitle1)
	$panel1.Controls.Add($txtArtist1)
	$panel1.Controls.Add($labelArtist)
	$panel1.Controls.Add($labelTitle)
	$panel1.Location = '7, 4'
	$panel1.Margin = '4, 4, 4, 4'
	$panel1.Name = 'panel1'
	$panel1.Size = '304, 100'
	$panel1.TabIndex = 7
	$panel1.add_Paint($panel1_Paint)
	#
	# txtTitle1
	#
	$txtTitle1.Location = '76, 4'
	$txtTitle1.Margin = '4, 4, 4, 4'
	$txtTitle1.Multiline = $True
	$txtTitle1.Name = 'txtTitle1'
	$txtTitle1.Size = '224, 50'
	$txtTitle1.TabIndex = 2
	#
	# txtArtist1
	#
	$txtArtist1.Location = '76, 62'
	$txtArtist1.Margin = '4, 4, 4, 4'
	$txtArtist1.Multiline = $True
	$txtArtist1.Name = 'txtArtist1'
	$txtArtist1.Size = '224, 30'
	$txtArtist1.TabIndex = 3
	$txtArtist1.add_TextChanged($txtArtist1_TextChanged)
	#
	# labelArtist
	#
	$labelArtist.AutoSize = $True
	$labelArtist.Font = 'Open Sans, 9pt, style=Bold'
	$labelArtist.Location = '4, 66'
	$labelArtist.Margin = '4, 0, 4, 0'
	$labelArtist.Name = 'labelArtist'
	$labelArtist.Size = '49, 26'
	$labelArtist.TabIndex = 6
	$labelArtist.Text = 'Artist'
	$labelArtist.UseCompatibleTextRendering = $True
	#
	# labelTitle
	#
	$labelTitle.AutoSize = $True
	$labelTitle.Font = 'Open Sans, 9pt, style=Bold'
	$labelTitle.Location = '4, 18'
	$labelTitle.Margin = '4, 0, 4, 0'
	$labelTitle.Name = 'labelTitle'
	$labelTitle.Size = '40, 26'
	$labelTitle.TabIndex = 5
	$labelTitle.Text = 'Title'
	$labelTitle.UseCompatibleTextRendering = $True
	#
	# btnCountMusic
	#
	$btnCountMusic.Location = '223, 32'
	$btnCountMusic.Margin = '4, 4, 4, 4'
	$btnCountMusic.Name = 'btnCountMusic'
	$btnCountMusic.Size = '100, 30'
	$btnCountMusic.TabIndex = 9
	$btnCountMusic.Text = 'Count'
	$btnCountMusic.UseCompatibleTextRendering = $True
	$btnCountMusic.UseVisualStyleBackColor = $True
	$btnCountMusic.add_Click($btnCountMusic_Click)
	#
	# panel5
	#
	$panel5.Controls.Add($lblMusic)
	$panel5.Controls.Add($labelMusicFilesDetected)
	$panel5.Location = '8, 24'
	$panel5.Margin = '4, 4, 4, 4'
	$panel5.Name = 'panel5'
	$panel5.Size = '207, 46'
	$panel5.TabIndex = 8
	#
	# lblMusic
	#
	$lblMusic.AutoSize = $True
	$lblMusic.Location = '180, 12'
	$lblMusic.Margin = '4, 0, 4, 0'
	$lblMusic.Name = 'lblMusic'
	$lblMusic.Size = '17, 21'
	$lblMusic.TabIndex = 7
	$lblMusic.Text = '...'
	$lblMusic.UseCompatibleTextRendering = $True
	$lblMusic.add_Click($lblMusic_Click)
	#
	# labelMusicFilesDetected
	#
	$labelMusicFilesDetected.AutoSize = $True
	$labelMusicFilesDetected.Font = 'Open Sans, 9pt, style=Bold'
	$labelMusicFilesDetected.Location = '8, 12'
	$labelMusicFilesDetected.Margin = '4, 0, 4, 0'
	$labelMusicFilesDetected.Name = 'labelMusicFilesDetected'
	$labelMusicFilesDetected.Size = '164, 26'
	$labelMusicFilesDetected.TabIndex = 6
	$labelMusicFilesDetected.Text = 'Music files detected:'
	$labelMusicFilesDetected.UseCompatibleTextRendering = $True
	$labelMusicFilesDetected.add_Click($labelMusicFilesDetected_Click)
	#
	# progressbar1
	#
	$progressbar1.Location = '13, 538'
	$progressbar1.Margin = '4, 4, 4, 4'
	$progressbar1.Name = 'progressbar1'
	$progressbar1.Size = '562, 29'
	$progressbar1.TabIndex = 1
	#
	# btnCompile
	#
	$btnCompile.Font = 'Open Sans, 7.8pt, style=Bold'
	$btnCompile.Location = '583, 538'
	$btnCompile.Margin = '4, 4, 4, 4'
	$btnCompile.Name = 'btnCompile'
	$btnCompile.Size = '100, 30'
	$btnCompile.TabIndex = 0
	$btnCompile.Text = 'Compile'
	$btnCompile.UseCompatibleTextRendering = $True
	$btnCompile.UseVisualStyleBackColor = $True
	$btnCompile.add_Click($btnCompile_Click)
	$panel5.ResumeLayout()
	$panel1.ResumeLayout()
	$panel8.ResumeLayout()
	$panel9.ResumeLayout()
	$panel10.ResumeLayout()
	$panelMusic.ResumeLayout()
	$grpbxMusic.ResumeLayout()
	$panel6.ResumeLayout()
	$Vidya.ResumeLayout()
	$form1.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $form1.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$form1.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$form1.add_FormClosed($Form_Cleanup_FormClosed)
	#Show the Form
	return $form1.ShowDialog()

} #End Function

#Call the form
Show-leGUI_psf | Out-Null
